### ISSUE TITLE
Crash when setting favorite

### ISSUE THREAD

**Issue by w0land** [PDXostc/navit#71]
bt

#0  0x080b76a1 in operator() (__closure=<synthetic pointer>) at /usr/src/debug/nxe-1.1/Navigation/NXE/src/app/navitquickproxy.cc:113
#1  call (arg=0xbfcf2968, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:494
#2  call<QtPrivate::List<>, void> (arg=0xbfcf2968, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:551
#3  QtPrivate::QFunctorSlotObject<NavitQuickProxy::NavitQuickProxy(const QString&, QQmlContext*, QObject*)::<lambda(const NXE::PointClicked&)>::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1,
    this_=0xb3604820, r=0xb361a600, a=0xbfcf2968, ret=0x0) at /usr/include/qt5/QtCore/qobject_impl.h:192
#4  0xb754bd3c in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5
#5  0xb754c7ab in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /lib/libQt5Core.so.5
#6  0x080f2d88 in LocationProxy::favoriteChanged (this=0xb361a600) at /usr/src/debug/nxe-1.1/src/app/moc_locationproxy.cpp:220
#7  0x080e8635 in LocationProxy::setFavorite (this=this@entry=0xb361a600, bFav=true)
    at /usr/src/debug/nxe-1.1/Navigation/NXE/src/app/locationproxy.cc:63
#8  0x080f4705 in LocationProxy::qt_metacall (this=0xb361a600, _c=QMetaObject::WriteProperty, _id=1, _a=0xbfcf2fa0)
    at /usr/src/debug/nxe-1.1/src/app/moc_locationproxy.cpp:191
#9  0xb752276d in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /lib/libQt5Core.so.5
#10 0xb706f1b7 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) () from /lib/libQt5Qml.so.5
#11 0xb7028de1 in QV4::QObjectWrapper::setProperty(QObject*, QV4::ExecutionContext*, QQmlPropertyData*, QV4::ValueRef) ()
   from /lib/libQt5Qml.so.5
#12 0xb702938c in QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionContext*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::ValueRef) () from /lib/libQt5Qml.so.5
#13 0xb70294cf in QV4::QObjectWrapper::put(QV4::Managed*, QV4::String*, QV4::ValueRef) () from /lib/libQt5Qml.so.5
#14 0xb7031e29 in QV4::Runtime::setProperty(QV4::ExecutionContext*, QV4::ValueRef, QV4::String*, QV4::ValueRef) ()
   from /lib/libQt5Qml.so.5
#15 0xaf13a2d5 in ?? ()
#16 0xb6fdd162 in QV4::SimpleScriptFunction::call(QV4::Managed*, QV4::CallData*) () from /lib/libQt5Qml.so.5
#17 0xb70e0f7a in QQmlJavaScriptExpression::evaluate(QQmlContextData*, QV4::ValueRef, QV4::CallData*, bool*) () from /lib/libQt5Qml.so.5
#18 0xb707f65c in QQmlBoundSignalExpression::evaluate(void**) () from /lib/libQt5Qml.so.5
#19 0xb7080057 in QQmlBoundSignal_callback(QQmlNotifierEndpoint*, void**) () from /lib/libQt5Qml.so.5
#20 0xb70c074d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /lib/libQt5Qml.so.5
#21 0xb7057da8 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /lib/libQt5Qml.so.5
#22 0xb754bbb9 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5

**Comment by w0land** [comment]
This should be fixed by 4912a66a1bb959aa9374cc4cee4aa5b4632f260f
